export const staticPages:Record<string,{title:string;description:string}>={
 '/':{title:'VESTIGIA',description:'Explore the VESTIGIA collection.'},'/shop':{title:'Shop',description:'Explore the VESTIGIA collection.'},
 '/about':{title:'About VESTIGIA',description:'Learn about VESTIGIA and our approach to clothing.'},'/story':{title:'Our Story',description:'Discover the story behind VESTIGIA.'},'/lookbook':{title:'Lookbook',description:'Explore VESTIGIA looks and collections.'},'/journal':{title:'Journal',description:'Stories and product guides from VESTIGIA.'},
 '/contact':{title:'Contact VESTIGIA',description:'Contact VESTIGIA for product and order support.'},'/faq':{title:'Frequently Asked Questions',description:'Answers to questions about shopping with VESTIGIA.'},'/shipping-policy':{title:'Shipping Policy',description:'Read VESTIGIA shipping information before ordering.'},'/refund-policy':{title:'Returns and Refunds',description:'Read the VESTIGIA returns and refund policy.'},'/privacy-policy':{title:'Privacy Policy',description:'How VESTIGIA handles your personal information.'},'/terms-of-service':{title:'Terms of Service',description:'Terms for using and shopping at VESTIGIA.'}};
export const privateRoute=(path:string)=>/^\/(admin|account|checkout|cart|activate|activate-account|homepage-preview|newsletter)(\/|$)/.test(path);
export function urlPolicy(path:string,search='') {const params=new URLSearchParams(search),catalog=path==='/shop'||path.startsWith('/collections/');const faceted=catalog&&['search','q','sort','category','color','size','min','max','availability'].some(k=>params.has(k));const page=Math.min(100,Math.max(1,Math.floor(Number(params.get('page'))||1)));return {noIndex:privateRoute(path)||faceted,canonical:path+(catalog&&page>1&&!faceted?'?page='+page:''),page};}
// Register only deployed, translated equivalents. Empty registry intentionally emits no hreflang.
export type Translation={language:string;url:string};
export function hreflangLinks(translations:Translation[]){return translations.filter(t=>/^(en|it-IT|fr|de|x-default)$/.test(t.language)&&/^https:\/\//.test(t.url));}
export const robotsText=(base:string,staging=false)=>staging?'User-agent: *\nDisallow: /\n':
 'User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /api/\nAllow: /api/feeds/\nDisallow: /homepage-preview\nDisallow: /checkout\nDisallow: /cart\nDisallow: /account\nSitemap: '+base+'/sitemap.xml\n';
