import { journalArticles } from '../../src/data.js';
import { renderToString } from 'react-dom/server';
import PublicStorefront from '../../shared/PublicStorefront.js';
import { catalog } from '../../shared/seo/catalog.js';
import { productSchema,productTitle,productDescription,canonicalProduct,currencyFrom,SITE,slug } from '../../shared/seo/product.js';
import { urlPolicy,staticPages } from '../../shared/seo/policy.js';
import type { PublicSnapshot } from './publishedStorefront.js';
const escape=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const safeJson=(data:unknown)=>JSON.stringify(data).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
export function documentHead(template:string,{title,description,canonical,image,robots,schema=[]}:{title:string;description:string;canonical:string;image:string;robots:string;schema?:unknown[]}){
 const head='<title>'+escape(title)+'</title><meta name="description" content="'+escape(description)+'"><link rel="canonical" href="'+escape(canonical)+'"><meta name="robots" content="'+robots+'"><meta property="og:site_name" content="VESTIGIA"><meta property="og:type" content="'+(canonical.includes('/product/')?'product':'website')+'"><meta property="og:title" content="'+escape(title)+'"><meta property="og:description" content="'+escape(description)+'"><meta property="og:url" content="'+escape(canonical)+'"><meta property="og:image" content="'+escape(image)+'"><meta property="og:locale" content="en_US"><meta property="og:locale:alternate" content="it_IT"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="'+escape(title)+'"><meta name="twitter:description" content="'+escape(description)+'"><meta name="twitter:image" content="'+escape(image)+'"><link rel="stylesheet" href="/public-document.css"><script id="vestigia-jsonld-schema" type="application/ld+json">'+safeJson(schema)+'</script>';
 return template.replace(/<title>[\s\S]*?<\/title>/gi,'').replace(/<meta\b[^>]*(?:name|property)=["'](?:description|robots|og:[^"']*|twitter:[^"']*)["'][^>]*>/gi,'').replace(/<link\b[^>]*rel=["'](?:canonical|alternate)["'][^>]*>/gi,'').replace(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>[\s\S]*?<\/script>/gi,'').replace('</head>',()=>head+'</head>');
}
export function storefrontHtml(template:string,snapshot:PublicSnapshot,pathname='/',search='') {
 const seo=snapshot.config.seo,home=pathname==='/',base=(process.env.PUBLIC_SITE_URL||SITE).replace(/\/+$/,''),policy=urlPolicy(pathname,search);
 const product=pathname.startsWith('/product/')?snapshot.products.find(p=>(p.slug||String(p.id))===decodeURIComponent(pathname.slice(9))):undefined;
 const listing=catalog(snapshot.config,snapshot.products,pathname,search);
 const canonical=product?canonicalProduct(product,base):new URL(policy.canonical,base).href;
 const title=product?productTitle(product):home?seo.title:listing.title+' | VESTIGIA';
 const description=product?productDescription(product):home?seo.description:listing.description;
 const image=new URL(product?(product.modelImage||product.image):seo.image,base).href;
 const organization={'@context':'https://schema.org','@type':['Organization','OnlineStore'],'@id':base+'/#organization',name:'VESTIGIA',url:base,logo:base+'/images/products/vestigia_logo.png',sameAs:['https://instagram.com/thevestigia','https://tiktok.com/@thevestigia'],contactPoint:{'@type':'ContactPoint',contactType:'customer service',email:'support@thevestigia.com',availableLanguage:['English','Italian']}};
 const website={'@context':'https://schema.org','@type':'WebSite','@id':base+'/#website',name:'VESTIGIA',alternateName:'VESTIGIA Official Online Store',url:base,inLanguage:'en',publisher:{'@id':base+'/#organization'},potentialAction:{'@type':'SearchAction',target:base+'/shop?q={search_term_string}','query-input':'required name=search_term_string'}};
 const schema:unknown[]=home?[organization,website]:[];
 if(product)schema.push(productSchema(product,currencyFrom(search),base));
 else if(!home)schema.push({'@context':'https://schema.org','@type':'CollectionPage',name:listing.title,description,url:canonical,mainEntity:{'@type':'ItemList',itemListElement:listing.items.slice(0,listing.pageSize*policy.page).map((p,i)=>({'@type':'ListItem',position:i+1,url:canonicalProduct(p,base)}))}});
 if(!home)schema.push({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{name:'Home',url:base+'/'},{name:'Shop',url:base+'/shop'},...(product?[{name:product.category,url:base+'/collections/'+slug(product.category)},{name:product.name,url:canonical}]:pathname==='/shop'?[]:[{name:listing.title,url:canonical}])].map((p,i)=>({'@type':'ListItem',position:i+1,name:p.name,item:p.url}))});
 const noIndex=process.env.SEO_NOINDEX==='true'||!seo.index||policy.noIndex||(!home&&!product&&!listing.items.length)||product?.robotsIndex===false;
 let html=documentHead(template,{title,description,canonical,image,robots:(noIndex?'noindex':'index')+', '+(product?.robotsFollow===false?'nofollow':'follow')+', max-image-preview:large',schema});
 if(process.env.SEO_NOINDEX==='true')html=html.replace('<html','<html data-noindex="true"');
 const markup=renderToString(<PublicStorefront config={snapshot.config} products={snapshot.products} pathname={pathname} search={search}/>);
 return html.replace(/<div id="root"><\/div>/,()=>'<div id="root">'+markup+'</div><script id="vestigia-public-data" type="application/json">'+safeJson(snapshot)+'</script>');
}
export function fallbackHtml(template:string,pathname:string,missing=false){
 const base=process.env.PUBLIC_SITE_URL||SITE,article=journalArticles.find(a=>pathname==='/journal/'+a.id),page=article?{title:article.title,description:article.excerpt}:staticPages[pathname];
 const canonical=new URL(pathname,base).href;
 const faqSchema={'@context':'https://schema.org','@type':'FAQPage',mainEntity:[{name:'Where do VESTIGIA garments ship from?','@type':'Question',acceptedAnswer:{'@type':'Answer',text:'All garments are dispatched directly from our luxury studio in Sri Lanka, where each piece undergoes meticulous hand-inspection prior to express shipment via DHL, FedEx, or UPS.'}},{name:'How long does shipping take?','@type':'Question',acceptedAnswer:{'@type':'Answer',text:'Standard express delivery takes 3 to 5 business days for Western Europe, North America, and Australia. Orders are processed within 24 to 48 hours.'}},{name:'Is complimentary shipping available?','@type':'Question',acceptedAnswer:{'@type':'Answer',text:'Yes, we offer complimentary express delivery worldwide on all orders exceeding $150 (€140 / ¥22,000).'}},{name:'What is your return policy?','@type':'Question',acceptedAnswer:{'@type':'Answer',text:'We offer a 30-day complimentary return period. Garments must be unworn, unwashed, with all original tags attached. Returns are refunded back to your original payment method.'}},{name:'How do VESTIGIA garments fit?','@type':'Question',acceptedAnswer:{'@type':'Answer',text:'Our garments feature a refined contemporary oversized silhouette with relaxed shoulders. We recommend choosing your standard size for the intended structured drop-shoulder fit, or sizing down for a closer fit.'}},{name:'What fabric quality does VESTIGIA use?','@type':'Question',acceptedAnswer:{'@type':'Answer',text:'We use 280 GSM (Grams per Square Meter) combed organic heavyweight cotton jersey, offering exceptional structure, softness, and longevity.'}}]};
 const fallbackSchemas:unknown[]=article?[{'@context':'https://schema.org','@type':'Article',headline:article.title,description:article.excerpt,image:new URL(article.image,base).href,mainEntityOfPage:canonical,publisher:{'@id':base+'/#organization'}}]:pathname==='/faq'?[faqSchema]:[];
 let html=documentHead(template,{title:missing?'Page not found | VESTIGIA':(page?.title||'VESTIGIA')+' | VESTIGIA',description:missing?'The requested page could not be found.':page?.description||'VESTIGIA secure customer area.',canonical,image:article?new URL(article.image,base).href:base+'/images/products/vestigia_logo.png',robots:missing||!page||process.env.SEO_NOINDEX==='true'?'noindex, follow':'index, follow',schema:fallbackSchemas});
 if(pathname==='/journal')html=html.replace('<div id="root"></div>',()=>'<div id="root"><main class="public-product"><nav><a href="/">Home</a> / <a href="/shop">Shop</a> / <a href="/lookbook">Lookbook</a></nav><h1>Journal</h1>'+journalArticles.map(a=>'<article><h2><a href="/journal/'+a.id+'">'+escape(a.title)+'</a></h2><p>'+escape(a.excerpt)+'</p></article>').join('')+'</main></div>');
 if(article)html=html.replace('<div id="root"></div>',()=>'<div id="root"><main class="public-product"><nav><a href="/">Home</a> / <a href="/journal">Journal</a></nav><article><h1>'+escape(article.title)+'</h1><img src="'+escape(article.image)+'" alt="'+escape(article.title)+'" width="1200" height="800" fetchpriority="high"><p>'+escape(article.excerpt)+'</p>'+article.content.map(p=>'<p>'+escape(p)+'</p>').join('')+'<a href="/shop">Explore the collection</a></article></main></div>');
 if(process.env.SEO_NOINDEX==='true')html=html.replace('<html','<html data-noindex="true"');
 return html;
}
