import type { HeroFocalPoints, Media } from '../../../shared/homepage';
import { resolveProductImageUrl } from '../../utils/productMedia';
type Props={settings:Media & HeroFocalPoints;onChange:(values:Partial<HeroFocalPoints>)=>void};
export default function HeroFocalEditor({settings,onChange}:Props) {
 return <fieldset><legend>Hero art direction</legend><p>Desktop and tablet use the desktop image. Mobile uses its own image, falling back to desktop when empty.</p><small>The current campaign source is square and its heads are near the top: start at Y = 0 for desktop/tablet. For a new landscape image, use the preview to adjust. Recommended desktop upload: 1920 × 1080 or 1920 × 1200.</small>{(['desktop','tablet','mobile'] as const).map(mode=>{
  const xKey=`${mode}FocalX` as const,yKey=`${mode}FocalY` as const;
  const image=mode==='mobile'?(settings.mobileImage||settings.image):settings.image;
  return <fieldset key={mode}><legend>{mode[0].toUpperCase()+mode.slice(1)} focal point</legend><button type="button" className="cms-focal-picker" aria-label={`Choose ${mode} focal point; arrow keys adjust by one percent`} onClick={e=>{if(e.detail===0)return;const rect=e.currentTarget.getBoundingClientRect();onChange({[xKey]:Math.round(Math.max(0,Math.min(100,(e.clientX-rect.left)/rect.width*100))),[yKey]:Math.round(Math.max(0,Math.min(100,(e.clientY-rect.top)/rect.height*100)))});}} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const key=e.key==='ArrowLeft'||e.key==='ArrowRight'?xKey:yKey;const delta=e.key==='ArrowLeft'||e.key==='ArrowUp'?-1:1;onChange({[key]:Math.max(0,Math.min(100,settings[key]+delta))});}}><img src={resolveProductImageUrl(image)} alt=""/><span aria-hidden="true" style={{left:`${settings[xKey]}%`,top:`${settings[yKey]}%`}}>+</span></button><div className="cms-focal-fields"><label>Horizontal X (%)<input type="number" min={0} max={100} step={1} value={settings[xKey]} onChange={e=>onChange({[xKey]:Number(e.target.value)})}/></label><label>Vertical Y (%)<input type="number" min={0} max={100} step={1} value={settings[yKey]} onChange={e=>onChange({[yKey]:Number(e.target.value)})}/></label></div><div className="cms-actions">{[['Top',0],['Center',50],['Bottom',100]].map(([label,value])=><button type="button" key={label} onClick={()=>onChange({[yKey]:Number(value)})}>{label}</button>)}</div></fieldset>;
 })}<p>Use Preview Draft to inspect the actual crop at desktop, tablet and mobile widths before publishing.</p></fieldset>;
}
