import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { newSection, sectionLabels, validateHomepage, type HomepageConfig, type HomepageRecord, type SectionType } from '../../../shared/homepage';
import { homepageApi } from '../../homepage/api';
import SectionEditor, { FooterEditor, TextField, Toggle } from './SectionEditor';
import { MediaPicker, Ordering, reordered } from './Pickers';
import './homepage-admin.css';
import ShopSettingsEditor from './ShopSettingsEditor';

export default function HomepageAdmin() {
 const [record,setRecord]=useState<HomepageRecord|null>(null),[draft,setDraft]=useState<HomepageConfig|null>(null),[active,setActive]=useState('hero'),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[drag,setDrag]=useState<number|null>(null),[preview,setPreview]=useState(false),[width,setWidth]=useState(390),[previewKey,setPreviewKey]=useState(0);
 const saved=useRef(''),navigate=useNavigate(),previewRef=useRef<HTMLElement>(null);
 useEffect(()=>{if(preview)previewRef.current?.scrollIntoView({block:'start',behavior:'instant'});},[preview,previewKey]);
 const dirty=!!draft&&JSON.stringify(draft)!==saved.current;
 const load=()=>{setBusy('Loading');homepageApi<HomepageRecord>('/admin/homepage').then(r=>{setRecord(r);setDraft(r.draft);saved.current=JSON.stringify(r.draft);setError('');}).catch(e=>setError(e.message)).finally(()=>setBusy(''));};
 useEffect(load,[]);
 useEffect(()=>{
  if(!dirty)return;
  const before=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};
  const click=(e:MouseEvent)=>{const a=(e.target as Element).closest('a');if(a&&a.origin===location.origin&&a.pathname!==location.pathname&&!window.confirm('You have unsaved homepage changes. Discard them?')){e.preventDefault();e.stopPropagation();}};
  // Protect browser back/forward as well as sidebar links with BrowserRouter.
  history.pushState({...history.state,homepageGuard:true},'',location.href);
  const pop=()=>{if(!window.confirm('You have unsaved homepage changes. Discard them?')){history.pushState({...history.state,homepageGuard:true},'',location.href);}else navigate(-1);};
  window.addEventListener('beforeunload',before);document.addEventListener('click',click,true);window.addEventListener('popstate',pop);
  return()=>{window.removeEventListener('beforeunload',before);document.removeEventListener('click',click,true);window.removeEventListener('popstate',pop);if(history.state?.homepageGuard&&location.pathname==='/admin/homepage')history.back();};
 },[dirty,navigate]);
 const save=async()=>{
  if(!draft||!record)return null;setBusy('Saving');setError('');
  try{const config=validateHomepage(draft);const result=await homepageApi<{revision:number;warnings:string[];updatedBy:string;updatedAt:string}>('/admin/homepage/draft',{method:'PUT',body:JSON.stringify({config,revision:record.revision})});saved.current=JSON.stringify(config);setDraft(config);setRecord({...record,draft:config,revision:result.revision,warnings:result.warnings,updatedAt:result.updatedAt,updatedBy:result.updatedBy});setMessage('Draft saved. The live homepage is unchanged.');return result.revision;}catch(e){setError(e instanceof Error?e.message:'Save failed');return null;}finally{setBusy('');}
 };
 const publish=async()=>{if(!record||!window.confirm('Publish homepage? The current draft will replace the live homepage.'))return;const revision=dirty?await save():record.revision;if(revision===null)return;setBusy('Publishing');setError('');try{const result=await homepageApi<{publishedRevision:number;publishedAt:string;warnings:string[]}>('/admin/homepage/publish',{method:'POST',body:JSON.stringify({revision})});setRecord(r=>r?{...r,...result,published:draft!}:r);setMessage('Homepage published successfully.');window.dispatchEvent(new Event('homepage-published'));localStorage.setItem('vestigia_homepage_published',String(Date.now()));}catch(e){setError(e instanceof Error?e.message:'Publish failed');}finally{setBusy('');}};
 const previewDraft=async()=>{if(dirty&&await save()===null)return;setPreviewKey(v=>v+1);setPreview(true);};
 if(!draft||!record)return <div className="cms-builder"><h1>Homepage</h1><p role={error?'alert':'status'}>{error||'Loading homepage manager...'}</p>{error&&<button onClick={load}>Retry</button>}</div>;
 const sections=[...draft.sections].sort((a,b)=>a.sortOrder-b.sortOrder),selected=sections.find(s=>s.id===active);
 const updateSections=(items:typeof sections)=>setDraft({...draft,sections:items.map((s,sortOrder)=>({...s,sortOrder}))});
 const duplicate=()=>{if(!selected||['hero','announcement','newsletter'].includes(selected.type))return;const clone=structuredClone(selected);clone.id=crypto.randomUUID();clone.label+=' (copy)';updateSections([...sections,clone]);setActive(clone.id);};
 return <div className="cms-builder"><header className="cms-toolbar"><div><p className="cms-kicker">STOREFRONT / CONTENT</p><h1>Homepage <span className="cms-status">{dirty?'Unsaved':record.revision===record.publishedRevision?'Published':'Draft'}</span></h1><p>Manage the content and layout of the Vestigia storefront homepage.</p></div><div className="cms-actions"><button disabled={!!busy} onClick={()=>void previewDraft()}>Preview Draft</button><button disabled={!!busy||!dirty} onClick={()=>void save()}>Save Draft</button><button className="cms-primary" disabled={!!busy} onClick={()=>void publish()}>Publish</button></div></header><p className="cms-meta">Last published: {new Date(record.publishedAt).toLocaleString()} · Modified: {new Date(record.updatedAt).toLocaleString()} · By {record.updatedBy}</p>{busy&&<p role="status">{busy}...</p>}{message&&<p className="cms-success" role="status">{message}</p>}{error&&<div className="cms-error" role="alert">{error}<button onClick={()=>{if(!dirty||window.confirm('Discard local edits and reload the saved draft?'))load();}}>Reload saved draft</button></div>}{record.warnings.map(w=><p className="cms-warning" key={w}>{w}</p>)}
 <div className="cms-workspace"><aside className="cms-section-list"><h2>Sections</h2><p>Desktop, tablet and mobile share these sections, content and order. Drag to reorder on all devices. Announcement stays above navigation.</p>{sections.map((section,index)=><div key={section.id} className={`cms-section-row ${active===section.id?'selected':''}`} draggable onDragStart={()=>setDrag(index)} onDragEnd={()=>setDrag(null)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(drag!==null)updateSections(reordered(sections,drag,index));setDrag(null);}}><button className="cms-section-name" onClick={()=>setActive(section.id)}>⠿ {section.label}</button><input type="checkbox" aria-label={`Show ${section.label} on all devices`} checked={section.enabled} onChange={e=>updateSections(sections.map(s=>s.id===section.id?{...s,enabled:e.target.checked}:s))}/><Ordering index={index} count={sections.length} move={(from,to)=>updateSections(reordered(sections,from,to))}/></div>)}<label>Add section<select value="" onChange={e=>{if(!e.target.value)return;const section=newSection(e.target.value as SectionType,crypto.randomUUID());section.enabled=false;updateSections([...sections,section]);setActive(section.id);}}><option value="">Choose section type</option>{(['product_carousel','manifesto','editorial_banner','editorial_split','lookbook'] as SectionType[]).map(t=><option key={t} value={t}>{sectionLabels[t]}</option>)}</select></label><button onClick={()=>setActive('shop-settings')}>Shop &amp; collections</button><button onClick={()=>setActive('seo')}>SEO settings</button><button onClick={()=>setActive('footer')}>Footer navigation</button></aside>
 <main className="cms-edit-panel">{selected&&<><SectionEditor key={selected.id} section={selected} onChange={next=>updateSections(sections.map(s=>s.id===next.id?next:s))}/>{!['hero','announcement','newsletter'].includes(selected.type)&&<div className="cms-actions"><button onClick={duplicate}>Duplicate section</button><button onClick={()=>{if(window.confirm(`Remove ${selected.label} from the draft?`)){updateSections(sections.filter(s=>s.id!==selected.id));setActive('hero');}}}>Remove section</button></div>}</>}{active==='seo'&&<div className="cms-editor"><h2>Homepage SEO</h2><TextField label="SEO title" value={draft.seo.title} onChange={title=>setDraft({...draft,seo:{...draft.seo,title}})}/><TextField label="Meta description" multiline value={draft.seo.description} onChange={description=>setDraft({...draft,seo:{...draft.seo,description}})}/><MediaPicker label="Open Graph image" value={draft.seo.image} onChange={image=>setDraft({...draft,seo:{...draft.seo,image}})}/><TextField label="Canonical URL" value={draft.seo.canonical} onChange={canonical=>setDraft({...draft,seo:{...draft.seo,canonical}})}/><Toggle label="Allow search engine indexing" value={draft.seo.index} onChange={index=>setDraft({...draft,seo:{...draft.seo,index}})}/><div className="cms-search-snippet"><small>{draft.seo.canonical}</small><h3>{draft.seo.title}</h3><p>{draft.seo.description}</p></div></div>}{active==='shop-settings'&&<ShopSettingsEditor config={draft} onChange={shop=>setDraft({...draft,shop})}/>} {active==='footer'&&<FooterEditor value={draft.footer} onChange={footer=>setDraft({...draft,footer})}/>}</main></div>
 {preview&&<section ref={previewRef} className="cms-preview" aria-label="Draft preview"><div className="cms-actions"><h2>Draft preview</h2>{[[1440,'Desktop'],[768,'Tablet'],[390,'Mobile']].map(([size,label])=><button key={size} aria-pressed={width===size} onClick={()=>setWidth(Number(size))}>{label}</button>)}<button onClick={()=>setPreview(false)}>Close preview</button></div><p>Only authenticated admins can load this draft. Width: {width}px.</p><div className="cms-preview-scroll"><iframe key={previewKey} title="Unpublished homepage preview" src="/homepage-preview" style={{width,height:820}} /></div></section>}
 </div>;
}

