import { useEffect, useState } from 'react';
import type { Product } from '../../data';
import { homepageApi } from '../../homepage/api';
import { resolveProductImageUrl } from '../../utils/productMedia';
import { useCurrency } from '../../context/CurrencyContext';
import { moneyLabel } from '../../utils/money';

export function Ordering({index,count,move}: {index:number;count:number;move:(from:number,to:number)=>void}) { return <span className="cms-order"><button type="button" aria-label="Move up" disabled={index===0} onClick={()=>move(index,index-1)}>↑</button><button type="button" aria-label="Move down" disabled={index===count-1} onClick={()=>move(index,index+1)}>↓</button></span>; }
export function reordered<T>(items:T[],from:number,to:number) { const next=[...items];const [item]=next.splice(from,1);next.splice(to,0,item);return next; }
export function ProductPicker({ids,onChange}: {ids:number[];onChange:(ids:number[])=>void}) {
 const [query,setQuery]=useState(''),[page,setPage]=useState(0),[result,setResult]=useState<{items:Product[];total:number}>({items:[],total:0}),[selected,setSelected]=useState<Product[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[drag,setDrag]=useState<number|null>(null);
 const {currency}=useCurrency();
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>{setLoading(true);homepageApi<{items:Product[];total:number}>(`/admin/homepage/products?q=${encodeURIComponent(query)}&page=${page}`,{signal:controller.signal}).then(r=>{setResult(r);setError('');}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},250);return()=>{clearTimeout(timer);controller.abort();};},[query,page]);
 useEffect(()=>{if(!ids.length){setSelected([]);return;}const controller=new AbortController();homepageApi<{items:Product[]}>(`/admin/homepage/products?ids=${ids.join(',')}`,{signal:controller.signal}).then(r=>setSelected(r.items)).catch(()=>{});return()=>controller.abort();},[ids.join(',')]);
 const move=(from:number,to:number)=>onChange(reordered(ids,from,to));
 const row=(p:Product)=> <><img src={resolveProductImageUrl(p.productImage||p.image)} alt="" width={40} height={50}/><span><strong>{p.name}</strong><small>{p.sku||'No SKU'} · {p.category} · {p.prices?.[currency]?moneyLabel(p.prices[currency]!.priceMinor,currency):'Unavailable in this market'} · {Object.values(p.inventory||{}).some(n=>n>0)?'In stock':'Out of stock'}</small></span></>;
 return <div className="cms-picker"><h4>Selected products — drag to reorder</h4>{ids.map((id,index)=>{const p=selected.find(p=>p.id===id);return <div className="cms-product-row" key={id} draggable onDragStart={()=>setDrag(index)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(drag!==null)move(drag,index);setDrag(null);}}>{p?row(p):<span>Product #{id} — unavailable or loading</span>}<Ordering index={index} count={ids.length} move={move}/><button type="button" onClick={()=>onChange(ids.filter(n=>n!==id))}>Remove</button></div>;})}
 <label>Search products by name, SKU or category<input value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} placeholder="Search products"/></label>{loading&&<p role="status">Loading products…</p>}{error&&<p role="alert">{error}</p>}{result.items.map(p=><div className="cms-product-row" key={p.id}>{row(p)}<button type="button" disabled={ids.includes(p.id)||ids.length>=24} onClick={()=>onChange([...ids,p.id])}>{ids.includes(p.id)?'Selected':'Add'}</button></div>)}<div className="cms-actions"><button type="button" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{page+1} / {Math.max(1,Math.ceil(result.total/12))}</span><button type="button" disabled={(page+1)*12>=result.total} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>;
}
export function CollectionPicker({value,onChange}: {value:string;onChange:(value:string)=>void}) {
 const [categories,setCategories]=useState<{id:string;name:string;count:number}[]>([]),[error,setError]=useState(''),[query,setQuery]=useState('');
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>{homepageApi<typeof categories>('/admin/homepage/categories?q='+encodeURIComponent(query),{signal:controller.signal}).then(setCategories).catch(e=>{if(!controller.signal.aborted)setError(e.message);});},200);return()=>{clearTimeout(timer);controller.abort();};},[query]);
 return <><label>Search category collections<input value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Category collection<select value={value} onChange={e=>onChange(e.target.value)}><option value="">Choose a category</option>{value&&!categories.some(c=>c.id===value)&&<option value={value}>{value}</option>}{categories.map(c=><option key={c.id} value={c.id}>{c.name} ({c.count})</option>)}</select><small>The current catalog groups collections by category.</small>{error&&<span role="alert">{error}</span>}</label></>;
}
type Asset={url:string;name:string;bytes:number;mime:string;width?:number;height?:number};
export function MediaPicker({label,value,onChange}: {label:string;value:string;onChange:(value:string)=>void}) {
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[page,setPage]=useState(0),[assets,setAssets]=useState<{items:Asset[];total:number}>({items:[],total:0}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!open)return;const controller=new AbortController();const timer=setTimeout(()=>{homepageApi<typeof assets>(`/admin/homepage/media?q=${encodeURIComponent(query)}&page=${page}`,{signal:controller.signal}).then(setAssets).catch(e=>{if(!controller.signal.aborted)setError(e.message);});},200);return()=>{clearTimeout(timer);controller.abort();};},[open,query,page]);
 const upload=async(file:File|undefined)=>{if(!file)return;if(file.size>5*1024*1024){setError('Choose an image under 5 MB.');return;}setBusy(true);setError('');try{const body=new FormData();body.append('file',file);const result=await homepageApi<{url:string}>('/upload',{method:'POST',body});onChange(result.url);}catch(e){setError(e instanceof Error?e.message:'Upload failed');}finally{setBusy(false);}};
 return <fieldset className="cms-media"><legend>{label}</legend>{value&&<img className="cms-media-preview" src={resolveProductImageUrl(value)} alt={`${label} preview`} onLoad={e=>{if(!value.startsWith("/"))return;const image=e.currentTarget;void homepageApi("/admin/homepage/media",{method:"POST",body:JSON.stringify({url:value,width:image.naturalWidth,height:image.naturalHeight})}).catch(()=>{});}}/>}<label>Image URL<input value={value} onChange={e=>onChange(e.target.value)} placeholder="/images/… or https://…"/></label><div className="cms-actions"><label className="cms-upload">{busy?'Uploading…':'Upload / replace'}<input type="file" accept="image/png,image/jpeg,image/webp,image/avif" disabled={busy} onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/></label><button type="button" onClick={()=>setOpen(v=>!v)}>{open?'Close library':'Select existing media'}</button>{value&&<button type="button" onClick={()=>onChange('')}>Clear selection</button>}</div>{error&&<p role="alert">{error}</p>}{open&&<div><label>Search media<input value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label><div className="cms-media-grid">{assets.items.map(a=><button key={a.url} type="button" onClick={()=>{onChange(a.url);setOpen(false);}}><img src={resolveProductImageUrl(a.url)} alt="" loading="lazy"/><span>{a.name}</span><small>{Math.round(a.bytes/1024)} KB · {a.mime}</small></button>)}</div><div className="cms-actions"><button type="button" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><button type="button" disabled={(page+1)*18>=assets.total} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>}</fieldset>;
}
