import type { HomepageSection, LinkContent, HomepageConfig, GalleryItem, Media } from '../../../shared/homepage';
import { newSection } from '../../../shared/homepage';
import { CollectionPicker, MediaPicker, Ordering, ProductPicker, reordered } from './Pickers';
import HeroFocalEditor from './HeroFocalEditor';
import HotspotEditor from './HotspotEditor';

export function TextField({label,value,onChange,multiline=false}: {label:string;value:string;onChange:(value:string)=>void;multiline?:boolean}) {return <label>{label}{multiline?<textarea rows={4} value={value} onChange={e=>onChange(e.target.value)}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>}</label>;}
export function SelectField({label,value,options,onChange}: {label:string;value:string|number;options:readonly (string|number)[];onChange:(value:string)=>void}) {return <label>{label}<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o} value={o}>{String(o).replaceAll('_',' ')}</option>)}</select></label>;}
export function Toggle({label,value,onChange}: {label:string;value:boolean;onChange:(value:boolean)=>void}) {return <label className="cms-toggle"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/>{label}</label>;}
export function LinkEditor({label,value,onChange}: {label:string;value:LinkContent;onChange:(value:LinkContent)=>void}) {return <fieldset><legend>{label}</legend><TextField label="Label" value={value.label} onChange={v=>onChange({...value,label:v})}/><TextField label="Link" value={value.url} onChange={v=>onChange({...value,url:v})}/></fieldset>;}
function MediaFields({value,onChange}: {value:Media;onChange:(patch:Partial<Media>)=>void}) {return <><MediaPicker label="Desktop image" value={value.image} onChange={image=>onChange({image})}/><MediaPicker label="Mobile image (optional)" value={value.mobileImage} onChange={mobileImage=>onChange({mobileImage})}/><TextField label="Image alt text" value={value.alt} onChange={alt=>onChange({alt})}/><SelectField label="Desktop crop" value={value.desktopPosition} options={['left','center','right']} onChange={desktopPosition=>onChange({desktopPosition:desktopPosition as Media['desktopPosition']})}/><SelectField label="Mobile crop" value={value.mobilePosition} options={['left','center','right']} onChange={mobilePosition=>onChange({mobilePosition:mobilePosition as Media['mobilePosition']})}/></>;}
export default function SectionEditor({section,onChange}: {section:HomepageSection;onChange:(section:HomepageSection)=>void}) {
 const s=section.settings;
 const patch=(values:object)=>onChange({...section,settings:{...s,...values}} as HomepageSection);
 const text=(key:string,label:string,multiline=false)=><TextField key={key} label={label} value={String((s as unknown as Record<string,unknown>)[key]??'')} onChange={value=>patch({[key]:value})} multiline={multiline}/>;
 const select=(key:string,label:string,options:readonly (string|number)[],numeric=false)=><SelectField key={key} label={label} value={String((s as unknown as Record<string,unknown>)[key])} options={options} onChange={value=>patch({[key]:numeric?Number(value):value})}/>;
 const toggle=(key:string,label:string)=><Toggle key={key} label={label} value={Boolean((s as unknown as Record<string,unknown>)[key])} onChange={value=>patch({[key]:value})}/>;
 return <div className="cms-editor"><h2>{section.label}</h2><TextField label="Internal section name" value={section.label} onChange={label=>onChange({...section,label})}/><Toggle label="Visible on all devices" value={section.enabled} onChange={enabled=>onChange({...section,enabled})}/>
 {'heading' in s&&<fieldset><legend>Content</legend>{text('eyebrow','Eyebrow')}{text('heading','Heading')}{text('body','Description',true)}<LinkEditor label="Primary CTA" value={s.cta} onChange={cta=>patch({cta})}/><LinkEditor label="Secondary CTA (optional)" value={s.secondaryCta} onChange={secondaryCta=>patch({secondaryCta})}/>{select('alignment','Text alignment',['left','center','right'])}{select('textWidth','Text width',['narrow','medium','wide'])}</fieldset>}
 {select('background','Background',['warm','ivory','stone','black'])}
 {'image' in s&&<fieldset><legend>Photography</legend><MediaFields value={s} onChange={values=>patch(section.type==='hero'?{...values,...(values.desktopPosition?{desktopFocalX:values.desktopPosition==='left'?0:values.desktopPosition==='right'?100:50}:{}),...(values.mobilePosition?{mobileFocalX:values.mobilePosition==='left'?0:values.mobilePosition==='right'?100:50}:{})}:values)}/></fieldset>}
 {section.type==='hero'&&<HeroFocalEditor settings={section.settings} onChange={patch}/>}
 {'overlay' in s&&<fieldset><legend>Banner layout</legend>{select('vertical','Vertical text position',['top','center','bottom'])}{select('overlay','Overlay strength',['none','light','medium','dark'])}{select('textTheme','Text theme',['light','dark'])}{select('desktopHeight','Desktop height',['compact','standard','full'])}{select('mobileHeight','Mobile height',['compact','standard','full'])}</fieldset>}
 {section.type==='hero'&&<HotspotEditor settings={section.settings} onChange={patch}/>}
 {section.type==='product_carousel'&&<><fieldset><legend>Product selection</legend>{select('source','Product source',['manual','newest','category','best_selling'])}<small>Newest uses catalog insertion order. Best selling uses paid orders only.</small>{section.settings.source==='manual'&&<ProductPicker ids={section.settings.productIds} onChange={productIds=>patch({productIds})}/>} {section.settings.source==='category'&&<CollectionPicker value={section.settings.category} onChange={category=>patch({category})}/>}{section.settings.source!=='manual'&&section.settings.source!=='best_selling'&&select('sort','Sort',['newest','oldest','price_asc','price_desc'])}<label>Maximum products<input type="number" min={1} max={24} value={section.settings.maxProducts} onChange={e=>patch({maxProducts:Number(e.target.value)})}/></label><details><summary>Excluded products</summary><ProductPicker ids={section.settings.excludedIds} onChange={excludedIds=>patch({excludedIds})}/></details></fieldset><fieldset><legend>Presentation</legend>{select('layout','Desktop layout',['carousel','grid','lead'])}{select('desktopItems','Desktop items',[3,4,4.5],true)}{select('tabletItems','Tablet items',[2,2.5,3],true)}{select('mobileItems','Mobile items',[1.1,1.2,1.25,1.3],true)}{toggle('arrows','Show arrows')}{toggle('wishlist','Show wishlist')}{toggle('quickAdd','Show Quick Add')}{toggle('colors','Show colors')}{toggle('badges','Show badge')}{text('badge','Badge label (blank uses product badge)')}{toggle('autoplay','Autoplay (pauses on interaction)')}{toggle('loop','Loop')}</fieldset></>}
 {section.type==='editorial_split'&&<>{select('layout','Desktop layout',['image_left','image_right'])}{select('ratio','Image ratio',['portrait','landscape','editorial'])}</>}
 {section.type==='lookbook'&&<fieldset><legend>Gallery</legend>{select('layout','Desktop layout',['grid','carousel'])}{section.settings.items.map((item,index)=><details key={item.id}><summary>{item.caption||`Image ${index+1}`}</summary><Ordering index={index} count={section.settings.items.length} move={(from,to)=>patch({items:reordered(section.settings.items,from,to)})}/><MediaFields value={item} onChange={value=>patch({items:section.settings.items.map((i,n)=>n===index?{...i,...value}:i)})}/><TextField label="Caption" value={item.caption} onChange={caption=>patch({items:section.settings.items.map((i,n)=>n===index?{...i,caption}:i)})}/><TextField label="Optional link" value={item.url} onChange={url=>patch({items:section.settings.items.map((i,n)=>n===index?{...i,url}:i)})}/><Toggle label="Enabled" value={item.enabled} onChange={enabled=>patch({items:section.settings.items.map((i,n)=>n===index?{...i,enabled}:i)})}/><button type="button" onClick={()=>patch({items:section.settings.items.filter((_,n)=>n!==index)})}>Remove image</button></details>)}<button type="button" disabled={section.settings.items.length>=12} onClick={()=>{const base=newSection('editorial_split','temp').settings;const item:GalleryItem={id:crypto.randomUUID(),image:base.image,mobileImage:'',alt:base.alt,desktopPosition:'center',mobilePosition:'center',caption:'',url:'',enabled:true};patch({items:[...section.settings.items,item]});}}>Add gallery image</button></fieldset>}
 {section.type==='newsletter'&&<fieldset><legend>Subscription form</legend>{toggle('crest','Show crest')}{text('placeholder','Email placeholder')}{text('buttonLabel','Button label')}{text('successMessage','Success message')}{text('privacyCopy','Privacy copy',true)}</fieldset>}
 {section.type==='announcement'&&<fieldset><legend>Messages</legend>{toggle('rotation','Rotate messages')}{select('textTheme','Text theme',['light','dark'])}<label>Rotation interval (seconds)<input type="number" min={3} max={30} value={section.settings.interval} onChange={e=>patch({interval:Number(e.target.value)})}/></label>{section.settings.messages.map((m,index)=><fieldset key={m.id}><legend>Message {index+1}</legend><Ordering index={index} count={section.settings.messages.length} move={(from,to)=>patch({messages:reordered(section.settings.messages,from,to)})}/><TextField label="Message text" value={m.text} onChange={text=>patch({messages:section.settings.messages.map((v,n)=>n===index?{...v,text}:v)})}/><TextField label="Optional link" value={m.url} onChange={url=>patch({messages:section.settings.messages.map((v,n)=>n===index?{...v,url}:v)})}/><Toggle label="Enabled" value={m.enabled} onChange={enabled=>patch({messages:section.settings.messages.map((v,n)=>n===index?{...v,enabled}:v)})}/><button type="button" onClick={()=>patch({messages:section.settings.messages.filter((_,n)=>n!==index)})}>Remove message</button></fieldset>)}<button type="button" disabled={section.settings.messages.length>=10} onClick={()=>patch({messages:[...section.settings.messages,{id:crypto.randomUUID(),text:'New announcement',url:'',enabled:true}]})}>Add message</button></fieldset>}
 </div>;
}

export function FooterEditor({value,onChange}: {value:HomepageConfig['footer'];onChange:(v:HomepageConfig['footer'])=>void}) {
 return <div className="cms-editor"><h2>Footer navigation</h2><TextField label="Brand description" multiline value={value.description} onChange={description=>onChange({...value,description})}/><TextField label="Copyright" value={value.copyright} onChange={copyright=>onChange({...value,copyright})}/>{value.groups.map((g,index)=><fieldset key={g.id}><legend>{g.title}</legend><Ordering index={index} count={value.groups.length} move={(from,to)=>onChange({...value,groups:reordered(value.groups,from,to)})}/><TextField label="Group title" value={g.title} onChange={title=>onChange({...value,groups:value.groups.map((v,n)=>n===index?{...v,title}:v)})}/>{g.links.map((l,n)=><div key={n}><LinkEditor label={`Link ${n+1}`} value={l} onChange={link=>onChange({...value,groups:value.groups.map((v,i)=>i===index?{...v,links:v.links.map((item,j)=>j===n?{...item,...link}:item)}:v)})}/><Toggle label="Enabled" value={l.enabled} onChange={enabled=>onChange({...value,groups:value.groups.map((v,i)=>i===index?{...v,links:v.links.map((item,j)=>j===n?{...item,enabled}:item)}:v)})}/><Ordering index={n} count={g.links.length} move={(from,to)=>onChange({...value,groups:value.groups.map((v,i)=>i===index?{...v,links:reordered(v.links,from,to)}:v)})}/><button type="button" onClick={()=>onChange({...value,groups:value.groups.map((v,i)=>i===index?{...v,links:v.links.filter((_,j)=>j!==n)}:v)})}>Remove link</button></div>)}<button type="button" onClick={()=>onChange({...value,groups:value.groups.map((v,i)=>i===index?{...v,links:[...v.links,{label:'New link',url:'/shop',enabled:true}]}:v)})}>Add link</button><button type="button" onClick={()=>onChange({...value,groups:value.groups.filter((_,i)=>i!==index)})}>Remove group</button></fieldset>)}<button type="button" disabled={value.groups.length>=6} onClick={()=>onChange({...value,groups:[...value.groups,{id:crypto.randomUUID(),title:'Navigation',links:[]}]})}>Add navigation group</button><h3>Social links</h3>{value.socials.map((l,n)=><fieldset key={n}><LinkEditor label="Social link" value={l} onChange={link=>onChange({...value,socials:value.socials.map((item,i)=>i===n?{...item,...link}:item)})}/><Toggle label="Enabled" value={l.enabled} onChange={enabled=>onChange({...value,socials:value.socials.map((item,i)=>i===n?{...item,enabled}:item)})}/><button type="button" onClick={()=>onChange({...value,socials:value.socials.filter((_,i)=>i!==n)})}>Remove</button></fieldset>)}<button type="button" disabled={value.socials.length>=8} onClick={()=>onChange({...value,socials:[...value.socials,{label:'Social',url:'',enabled:false}]})}>Add social link</button></div>;
}
