import { useState } from 'react';
import { createPortal } from 'react-dom';
import { useScrollLock } from '../hooks/useScrollLock';
import { useDialogFocus } from '../hooks/useDialogFocus';
import { useCurrency } from '../context/CurrencyContext';
import { emptyShopFilters,filterShopProducts,type ShopFilters } from '../../shared/shop';
import type { Product } from '../data';
export default function FilterDrawer({products,value,onApply,onClose}: {products:Product[];value:ShopFilters;onApply:(v:ShopFilters)=>void;onClose:()=>void}) {
 const [draft,setDraft]=useState(value);const {currency}=useCurrency();useScrollLock(true);useDialogFocus(true,onClose,'.shop-filter-dialog');
 const sizes=[...new Set(products.flatMap(p=>p.sizes))],colors=[...new Set(products.flatMap(p=>p.colors))];
 let count=0,error='';try{count=filterShopProducts(products,draft,currency).length;}catch{error=`Enter valid ${currency} amounts, with minimum no higher than maximum.`;}
 const toggle=(key:'sizes'|'colors',value:string)=>setDraft({...draft,[key]:draft[key].includes(value)?draft[key].filter(v=>v!==value):[...draft[key],value]});
 return createPortal(<div className="shop-filter-backdrop" onClick={onClose}><section className="shop-filter-dialog" role="dialog" aria-modal="true" aria-labelledby="shop-filters-title" onClick={e=>e.stopPropagation()}><header><h2 id="shop-filters-title">Filters</h2><button onClick={onClose} aria-label="Close filters">✕</button></header><div className="shop-filter-content">{[['Size',sizes,'sizes'],['Color',colors,'colors']].map(([label,options,key])=><fieldset key={String(key)}><legend>{String(label)}</legend><div className="shop-filter-options">{(options as string[]).map(option=><label key={option}><input type="checkbox" checked={draft[key as 'sizes'|'colors'].includes(option)} onChange={()=>toggle(key as 'sizes'|'colors',option)}/>{option}</label>)}</div></fieldset>)}<fieldset><legend>Availability</legend>{[['','All pieces'],['in_stock','In stock'],['out_of_stock','Out of stock']].map(([v,label])=><label key={v}><input type="radio" name="availability" checked={draft.availability===v} onChange={()=>setDraft({...draft,availability:v})}/>{label}</label>)}</fieldset><fieldset><legend>Price · {currency}</legend><div className="shop-price-inputs"><label>Minimum<input inputMode="decimal" value={draft.min} onChange={e=>setDraft({...draft,min:e.target.value,priceCurrency:currency})}/></label><label>Maximum<input inputMode="decimal" value={draft.max} onChange={e=>setDraft({...draft,max:e.target.value,priceCurrency:currency})}/></label></div>{error&&<p role="alert">{error}</p>}</fieldset></div><footer><button onClick={()=>setDraft({...emptyShopFilters,sort:draft.sort})}>Clear all</button><button className="shop-filter-apply" disabled={!!error} onClick={()=>{onApply(draft);onClose();}}>Show {count} products</button></footer></section></div>,document.body);
}
